# Generated by Django 4.1.6 on 2023-02-16 06:53

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebSkill",
            fields=[],
            options={
                "verbose_name": "Skill",
                "verbose_name_plural": "Skills",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("main.skill",),
        ),
        migrations.CreateModel(
            name="WebUser",
            fields=[],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("auth.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
